version: '3.7'
services:
  rabbitmq-demo-app:
    image: ${GROUP_ID}/rabbitmq.demo.app.service:${SERVICE_VERSION:-latest}
    ports:
      - "8080:8080"
      - "5005:5005"
    user: root
    entrypoint: [ "bash", "rabbitmq-status.sh" ]
    volumes:
      - "./docker-logs:/workspace/rabbitmq-demo-app/logs"
      - "./rabbitmq-status.sh:/usr/local/bin/rabbitmq-status.sh"
    environment:
      #      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xms128m -Xmx256m"
      - "JAVA_OPTS=-Dapp.clients.scheme=http -Dserver.port=8080 -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xms128m -Xmx256m"
    networks:
      - ${GLOBAL_NETWORK:-services}